language: python

sudo: false

python:
- '3.7'
- '3.8'

install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
- conda activate test-environment
- conda install pytest pytest-cov coveralls pycodestyle cytoolz
- pip install .
- pip freeze

script:
- pycodestyle populationsim
- py.test --cov populationsim --cov-report term-missing

after_success:
- coveralls
# Build docs
- pip install sphinx numpydoc sphinx_rtd_theme==0.5.2
- cd docs
- make clean
- make html
- touch _build/html/.nojekyll

deploy:
  provider: pages
  local_dir: docs/_build/html
  skip_cleanup: true
  github_token: $GH_TOKEN_POPSIM  # Set in the settings page of the repository, as a secure variable
  keep_history: true
  on:
    branch: master
