
USE_CVX: False
INTEGERIZE_WITH_BACKSTOPPED_CONTROLS: True
RESCALE_SUBZONE_WEIGHTS: False
control_file_name: controls_original.csv


data_dir: data_calm


trace_geography:
  TAZ: 100
  TRACT: 10200

household_weight_col: WGTP
household_id_col: hh_id
total_hh_control: num_hh
max_expansion_factor: 30

# ordered list
input_pre_processor:
  - households
  - persons
  - geo_cross_walk
  # the following will eventually be created by setup_data_structures step
  - low_control_data
  - mid_control_data
  - meta_control_data

households:
  filename : seed_households.csv
  index_col: hh_id
  column_map:
    hhnum: hh_id

persons:
  # expression_filename: seed_persons_expressions.csv
  filename : seed_persons.csv
  column_map:
    hhnum: hh_id
    SPORDER: per_num

geo_cross_walk:
  filename : geo_cross_walk.csv
  column_map:
    TRACTCE: TRACT

low_control_data:
  filename : control_totals_maz.csv

mid_control_data:
  filename : control_totals_taz.csv

meta_control_data:
  filename : control_totals_meta.csv
  #filename : scaled_control_totals_meta.csv

geographies: [REGION, PUMA, TRACT, TAZ]
seed_geography: PUMA
crosswalk_data_table: geo_cross_walk

geography_settings:
  REGION:
    control_data_table: meta_control_data
    id_column: REGION
  PUMA:
    controls_table: seed_controls
    id_column: PUMA
  TRACT:
    control_data_table: mid_control_data
    id_column: TRACT
  TAZ:
    control_data_table: low_control_data
    id_column: TAZ
