
INTEGERIZE_WITH_BACKSTOPPED_CONTROLS: True
SUB_BALANCE_WITH_FLOAT_SEED_WEIGHTS: False
GROUP_BY_INCIDENCE_SIGNATURE: True
USE_SIMUL_INTEGERIZER: True

geographies: [REGION, PUMA, TRACT, TAZ]
seed_geography: PUMA

household_weight_col: WGTP
household_id_col: hh_id
total_hh_control: num_hh
max_expansion_factor: 30

#control_file_name: controls_original.csv
control_file_name: controls.csv

# scaled/unscaled meta_control_data file name specified below
data_dir: data_calm

trace_geography:
  TAZ: 100
  TRACT: 10200


# input_pre_processor input_table_list
input_table_list:
  - tablename: households
    filename : seed_households.csv
    index_col: hh_id
    column_map:
      SERIALNO: hh_id
  - tablename: persons
    # expression_filename: seed_persons_expressions.csv
    filename : seed_persons.csv
    column_map:
      SERIALNO: hh_id
      SPORDER: per_num
  - tablename: geo_cross_walk
    filename : geo_cross_walk.csv
    column_map:
      TRACTCE: TRACT
  - tablename: TAZ_control_data
    filename : control_totals_taz.csv
  - tablename: TRACT_control_data
    filename : control_totals_tract.csv
  - tablename: REGION_control_data
    #filename : control_totals_meta.csv
    filename : scaled_control_totals_meta.csv


# output_tables can specify either a list of output tables to include or to skip
# if neither is specified, then all checkpointed tables will be written

#output_tables:
#  action: skip
#  tables:
#    - households
#    - persons
#
#output_tables:
#  action: include
#  tables:
#    - expanded_household_ids


run_list:
  steps:
    - input_pre_processor
    - setup_data_structures
    - initial_seed_balancing
    - meta_control_factoring
    - final_seed_balancing
    - integerize_final_seed_weights
    - sub_balancing.geography=TRACT
    - sub_balancing.geography=TAZ
#    - expand_households
    - write_results
    - summarize

  resume_after: sub_balancing.geography=TRACT

repop:
  steps:
    - input_pre_processor.table_list=repop_input_table_list
    - repop_setup_data_structures
    - initial_seed_balancing.final=true
    - integerize_final_seed_weights.repop
    - repop_balancing
    # expand_households options are append or replace
    - expand_households.repop;append
    - write_results.repop
    - summarize.repop

  resume_after: summarize

repop_control_file_name: repop_controls.csv

repop_input_table_list:
  - taz_control_data:
    filename : repop_control_totals_taz.csv
    tablename: TAZ_control_data
