####################################################################
# PopulationSim Properties
####################################################################


# Algorithm/Software Configuration
# ------------------------------------------------------------------
INTEGERIZE_WITH_BACKSTOPPED_CONTROLS: True
SUB_BALANCE_WITH_FLOAT_SEED_WEIGHTS: False
GROUP_BY_INCIDENCE_SIGNATURE: True
USE_SIMUL_INTEGERIZER: True
USE_CVXPY: False
max_expansion_factor: 30


# Geographic Settings
# ------------------------------------------------------------------
geographies: [REGION, PUMA, TRACT, TAZ]
seed_geography: PUMA


# Tracing
# ------------------------------------------------------------------
trace_geography:
  TAZ: 100
  TRACT: 10200

  
# Data Directory
# ------------------------------------------------------------------
data_dir: data


# Input Data Tables
# ------------------------------------------------------------------
# input_pre_processor input_table_list
input_table_list:
  - tablename: households
    filename : seed_households.csv
    index_col: hh_id
    column_map:
      # not sure what SERIALNO is, but it is not unique
      #SERIALNO: hh_id
      hhnum: hh_id
  - tablename: persons
    # expression_filename: seed_persons_expressions.csv
    filename : seed_persons.csv
    column_map:
      # SERIALNO: hh_id
      hhnum: hh_id
      SPORDER: per_num
    # drop mixed type fields that appear to have been incorrectly generated
    drop_columns:
      - indp02
      - naicsp02
      - occp02
      - socp00
      - occp10
      - socp10
      - indp07
      - naicsp07
  - tablename: geo_cross_walk
    filename : geo_cross_walk.csv
    column_map:
      TRACTCE: TRACT
  - tablename: TAZ_control_data
    filename : control_totals_taz.csv
  - tablename: TRACT_control_data
    filename : control_totals_tract.csv
  - tablename: REGION_control_data
    #filename : control_totals_meta.csv
    filename : scaled_control_totals_meta.csv


# Reserved Column Names
# ------------------------------------------------------------------
household_weight_col: WGTP
household_id_col: hh_id
total_hh_control: num_hh


# Control Specification File Name
# ------------------------------------------------------------------
control_file_name: controls.csv


# Output Tables
# ------------------------------------------------------------------
# output_tables can specify either a list of output tables to include or to skip
# if neither is specified, then no tables will be written

output_tables:
  action: include
  tables:
    - expanded_household_ids


# Synthetic Population Output Specification
# ------------------------------------------------------------------
#

output_synthetic_population:
  household_id: hh_id
  households:
    filename: synthetic_households.csv
    columns:
      - NP
      - AGEHOH
      - HHINCADJ
      - NWESR
  persons:
    filename: synthetic_persons.csv
    columns:
      - per_num
      - AGEP
      - OSUTAG
      - OCCP


# Steps for base mode
# ------------------------------------------------------------------
run_list:
  steps:
    - input_pre_processor
    - setup_data_structures
    - initial_seed_balancing
    - meta_control_factoring
    - final_seed_balancing
    - integerize_final_seed_weights
    - sub_balancing.geography=TRACT
    - sub_balancing.geography=TAZ
    - expand_households
    - write_tables
    - write_synthetic_population
    - summarize

  #resume_after: expand_households

  
# Steps for repop mode
# ------------------------------------------------------------------
# "-m repop" command line option allows specification of repop run_list`
repop:
  steps:
    - input_pre_processor.table_list=repop_input_table_list
    - repop_setup_data_structures
    - initial_seed_balancing.final=true
    - integerize_final_seed_weights.repop
    - repop_balancing
    # expand_households options are append or replace
    - expand_households.repop;append
    - write_results.repop

  resume_after: summarize

  
# Control Specification File Name for repop mode
# ------------------------------------------------------------------
repop_control_file_name: repop_controls.csv


# Input Data Tables for repop mode
# ------------------------------------------------------------------
repop_input_table_list:
  - taz_control_data:
    filename : repop_control_totals_taz.csv
    tablename: TAZ_control_data
