####################################################################
# PopulationSim Properties
####################################################################


# Algorithm/Software Configuration
# ------------------------------------------------------------------
# This flag turns off integerization entirely (default False)
NO_INTEGERIZATION_EVER: True

# These settings are ignored if not integerizing
INTEGERIZE_WITH_BACKSTOPPED_CONTROLS: True
SUB_BALANCE_WITH_FLOAT_SEED_WEIGHTS: False
GROUP_BY_INCIDENCE_SIGNATURE: False

USE_SIMUL_INTEGERIZER: True

USE_CVXPY: False
max_expansion_factor: 4 # Default is 30
min_expansion_factor: 0.5


# Geographic Settings
# ------------------------------------------------------------------
# geographies: [Region, SUBREG_GRP, SUBREG] #, TAZ] #1, 44, 58, 1700
# seed_geography: SUBREG_GRP
# geographies: [Region, SUBREG_GRP, SUBREG_GRPDummy] 
# seed_geography: SUBREG_GRP
geographies: [Region, SUBREGCluster]
seed_geography: SUBREGCluster


# Tracing
# ------------------------------------------------------------------
# trace_geography:
#  TAZ: 100
#  TRACT: 10200

  
# Data Directory
# ------------------------------------------------------------------
#data_dir: data


# Input Data Tables
# ------------------------------------------------------------------
# input_pre_processor input_table_list
input_table_list:
  - tablename: households
    filename : seed_households.csv
    index_col: hh_id
    column_map:
      hhID: hh_id
  - tablename: persons
    filename : seed_persons.csv
    column_map:
      hhID: hh_id
      # personID: per_num
  - tablename: geo_cross_walk
    filename : geo_cross_walk.csv
  - tablename: SUBREGCluster_control_data
    filename : control_totals_subcluster.csv



# Reserved Column Names
# ------------------------------------------------------------------
household_weight_col: HHweight
household_id_col: hh_id
total_hh_control: num_hh


# Control Specification File Name
# ------------------------------------------------------------------
control_file_name: controls.csv


# Output Tables
# ------------------------------------------------------------------
# output_tables can specify either a list of output tables to include or to skip
# if neither is specified, then no tables will be written

output_tables:
  action: include
  tables:
    - summary_SUBREGCluster
    - expanded_household_ids
    - summary_hh_weights
    - incidence_table
    - household_groups
    - SUBREGCluster_weights
    #- trace_SUBREGClusterDummy_weights


# Synthetic Population Output Specification
# ------------------------------------------------------------------
#

# output_synthetic_population:
#   household_id: household_id
#   households:
#     filename: synthetic_households.csv
#     columns:
#       - HHSize
#       - HHIncome
#       - HHDwelling
#       - HHChildren
#   persons:
#     filename: synthetic_persons.csv
#     columns:
#       - per_num
#       - PAge
#       - PGender
#       - PEmp
#       - POcc
#       - PComm


# Steps for base mode
# ------------------------------------------------------------------
run_list:
  steps:
    - input_pre_processor
    - setup_data_structures
    - initial_seed_balancing
    - meta_control_factoring
    - final_seed_balancing
#    - integerize_final_seed_weights
    - expand_households
    - summarize
    - write_tables
  #  - write_synthetic_population

  #resume_after: expand_households
