
#store: calm_psim.h5


household_weight_col: WGTP
household_id_col: hh_id

# ordered list
input_pre_processor:
  - households
  - persons
  - geo_cross_walk
  # the following will eventually be created by setup_data_structures step
  - low_control_data
  - mid_control_data
  - meta_control_data

households:
  filename : seed_households.csv
  index_col: hh_id
  column_map:
    SERIALNO: hh_id

persons:
  # expression_filename: seed_persons_expressions.csv
  filename : seed_persons.csv
  column_map:
    SERIALNO: hh_id
    SPORDER: per_num

geo_cross_walk:
  filename : geo_cross_walk.csv
  column_map:
    TRACTCE: TRACT

low_control_data:
  filename : low_control_data.csv

mid_control_data:
  filename : mid_control_data.csv

meta_control_data:
  filename : meta_control_data.csv

geographies:
  seed:
    id_column: PUMA
  meta:
    id_column: irrelevant
  mid:
    control_data_table: mid_control_data
    id_column: TRACT
  low:
    control_data_table: low_control_data
    id_column: TAZ
  lower_level_geographies: [mid,low]
