
#store: calm_psim.h5


household_weight_col: WGTP
household_id_col: hh_id
total_hh_control: num_hh
max_expansion_factor: 5

# ordered list
input_pre_processor:
  - households
  - persons
  - geo_cross_walk
  # the following will eventually be created by setup_data_structures step
  - low_controls
  - mid_controls
  - meta_controls

households:
  filename : seed_households.csv
  index_col: hh_id
  column_map:
    SERIALNO: hh_id

persons:
  # expression_filename: seed_persons_expressions.csv
  filename : seed_persons.csv
  column_map:
    SERIALNO: hh_id
    SPORDER: per_num

geo_cross_walk:
  filename : geo_cross_walk.csv
  column_map:
    TRACTCE: TRACT

low_controls:
  filename : low_controls.csv

mid_controls:
  filename : mid_controls.csv

meta_controls:
  filename : meta_controls.csv

geographies:
  seed:
    id_column: PUMA
  meta:
    control_data_table: meta_controls
    id_column: DISTRICT
  mid:
    control_data_table: mid_controls
    id_column: TRACT
  low:
    control_data_table: low_controls
    id_column: TAZ

lower_level_geographies: [mid,low]
