
INTEGERIZE_WITH_BACKSTOPPED_CONTROLS: True
SUB_BALANCE_WITH_FLOAT_SEED_WEIGHTS: False
GROUP_BY_INCIDENCE_SIGNATURE: True
USE_SIMUL_INTEGERIZER: True
USE_CVXPY: True

#control_file_name: controls_original.csv
control_file_name: controls.csv

# scaled/unscaled meta_control_data file name specified below

data_dir: data_calm

# if output_tables is commented out, then all tables will be output EXCEPT skip_output_tables
#output_tables:
#  - expanded_household_ids
#  - REGION_1_summary
#  - TRACT_summary
#  - TAZ_summary

# list of tables to skip if output_tables not specified
skip_output_tables:
  - households
  - persons


trace_geography:
  TAZ: 100
  BLOCKGROUP: 51
  TRACT: 10200

household_weight_col: WGTP
household_id_col: hh_id
total_hh_control: num_hh
max_expansion_factor: 30

# ordered list
input_pre_processor:
  - households
  - persons
  - geo_cross_walk
  # the following will eventually be created by setup_data_structures step
  - taz_control_data
  - blockgroup_control_data
  - tract_control_data
  - meta_control_data

households:
  filename : seed_households.csv
  index_col: hh_id
  column_map:
    hhnum: hh_id

persons:
  # expression_filename: seed_persons_expressions.csv
  filename : seed_persons.csv
  column_map:
    hhnum: hh_id
    SPORDER: per_num

geo_cross_walk:
  filename : geo_cross_walk.csv
  column_map:
    TRACTCE: TRACT
    BLKGRP: BLOCKGROUP

taz_control_data:
  filename : control_totals_taz.csv

blockgroup_control_data:
  filename : control_totals_blockgroup.csv
  column_map:
    BLKGRP: BLOCKGROUP
    HHI1BASE: HHSIZE1
    HHI2BASE: HHSIZE2
    HHI3BASE: HHSIZE3
    HHI4BASE: HHSIZE4

tract_control_data:
  filename : control_totals_tract.csv

meta_control_data:
  #filename : control_totals_meta.csv
  filename : scaled_control_totals_meta.csv

geographies: [REGION, PUMA, TRACT, BLOCKGROUP, TAZ]
seed_geography: PUMA
crosswalk_data_table: geo_cross_walk

geography_settings:
  REGION:
    control_data_table: meta_control_data
    id_column: REGION
  PUMA:
    controls_table: seed_controls
    id_column: PUMA
  TRACT:
    control_data_table: tract_control_data
    id_column: TRACT
  BLOCKGROUP:
    control_data_table: blockgroup_control_data
    id_column: BLOCKGROUP
  TAZ:
    control_data_table: taz_control_data
    id_column: TAZ

models:
  - input_pre_processor
  - setup_data_structures
  - initial_seed_balancing
  - meta_control_factoring
  - final_seed_balancing
  - integerize_final_seed_weights
  - sub_balancing.geography=TRACT
  - sub_balancing.geography=BLOCKGROUP
  - sub_balancing.geography=TAZ
  # expand household and person records with final weights
  # to one household and one person record per weight with unique IDs
  - expand_population
  - summarize
  # write the household and person files to CSV files
  - write_results
